language: python
python:
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
script:
  - pytest --doctest-modules src/pylleo/**/*.py
  - pytest --black --flake8
